/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VENTANA;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import MODELO.Cliente;
import MODELO.Restaurante;
import MODELO.Plato;
import MODELO.Bebidas;
import MODELO.Postres;
import javax.swing.JOptionPane;



/**
 *
 * @author Jorge Vargas
 */
public class VentanaPrincipal extends javax.swing.JFrame {
private ArrayList<Cliente> listaClientes = new ArrayList<>();
private int idCliente = 1;
private DefaultTableModel modeloTabla;
private ArrayList<Restaurante> listaRestaurantes = new ArrayList<>();
private int idRestaurante = 1;
private DefaultTableModel modeloTablaRestaurantes;
private DefaultTableModel modeloTablaMesas;



    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        modeloTabla = new DefaultTableModel();
modeloTabla.addColumn("ID");
modeloTabla.addColumn("Nombre");
modeloTabla.addColumn("Email");
modeloTabla.addColumn("Teléfono");
modeloTabla.addColumn("Vegetariano");
jTable1.setModel(modeloTabla);
modeloTablaRestaurantes = new DefaultTableModel();
modeloTablaRestaurantes.addColumn("ID");
modeloTablaRestaurantes.addColumn("Nombre");
modeloTablaRestaurantes.addColumn("Dirección");
modeloTablaRestaurantes.addColumn("Teléfono");
jTable2.setModel(modeloTablaRestaurantes);
// Configurar tabla de mesas
modeloTablaMesas = new DefaultTableModel() {
    @Override
    public boolean isCellEditable(int row, int column) {
        // Solo la columna "Disponible" (índice 2) es editable
        return column == 2;
    }
};
modeloTablaMesas.addColumn("ID Mesa");
modeloTablaMesas.addColumn("Capacidad");
modeloTablaMesas.addColumn("Disponible");
jTable4.setModel(modeloTablaMesas);
jTable4.getModel().addTableModelListener(e -> {
    int row = e.getFirstRow();
    int column = e.getColumn();

    if (column == 2 && row != -1) {
        int indexRestaurante = comboRestaurantes.getSelectedIndex();
        if (indexRestaurante == -1) return;

        Restaurante restaurante = listaRestaurantes.get(indexRestaurante);
        String valor = (String) modeloTablaMesas.getValueAt(row, column);

        // Cambiar disponibilidad de la mesa
        boolean disponible = valor.equalsIgnoreCase("Sí") || valor.equalsIgnoreCase("Disponible");
        restaurante.getMesasDisponibles().get(row).setDisponible(disponible);
    }
});

// Limpiar y cargar el combo de restaurantes
actualizarCombosRestaurantes();

// Evento: cuando se selecciona un restaurante, se actualiza la tabla de mesas
comboRestaurantes.addActionListener(e -> mostrarMesasDeRestauranteSeleccionado());

 // Configurar modelos de tabla para inventarios
    configurarTablasInventario();
    
    // Actualizar combos de restaurantes
    actualizarCombosRestaurantes();
    
    // Configurar listeners
    configurarEventListeners();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panelTabs = new javax.swing.JTabbedPane();
        Clientespanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Registrarbotton = new javax.swing.JButton();
        nombreclifield = new javax.swing.JTextField();
        emailclifield = new javax.swing.JTextField();
        telefonoclifield = new javax.swing.JTextField();
        prefclifield = new javax.swing.JCheckBox();
        Restaurantespanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        nombrerestfield = new javax.swing.JTextField();
        direccionresfield = new javax.swing.JTextField();
        telefonoresfield = new javax.swing.JTextField();
        regisrestbtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        capacidadMesafield = new javax.swing.JTextField();
        agregarMesabtn = new javax.swing.JButton();
        menuspanel = new javax.swing.JPanel();
        Inventariospanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        comboRestaurantesInventario = new javax.swing.JComboBox<>();
        btnCargarInventario = new javax.swing.JButton();
        tabInventario = new javax.swing.JTabbedPane();
        panelPlatos = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaPlatos = new javax.swing.JTable();
        dasdasd = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtNombrePlato = new javax.swing.JTextField();
        txtDescripcionPlato = new javax.swing.JTextField();
        txtPrecioPlato = new javax.swing.JTextField();
        chkActivoPlato = new javax.swing.JCheckBox();
        btnAgregarPlato = new javax.swing.JButton();
        panelBebidas = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaBebidas = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtNombreBebida = new javax.swing.JTextField();
        txtDescripcionBebida = new javax.swing.JTextField();
        txtPrecioBebida = new javax.swing.JTextField();
        chkDisponibleBebida = new javax.swing.JCheckBox();
        chkAlcoholicaBebida = new javax.swing.JCheckBox();
        btnAgregarBebida = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        panelPostres = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaPostres = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtNombrePostre = new javax.swing.JTextField();
        txtDescripcionPostre = new javax.swing.JTextField();
        txtPrecioPostre = new javax.swing.JTextField();
        chkDisponiblePostre = new javax.swing.JCheckBox();
        chkAptoCeliacos = new javax.swing.JCheckBox();
        jLabel26 = new javax.swing.JLabel();
        txtCaloriasPostre = new javax.swing.JTextField();
        btnAgregarPostre = new javax.swing.JButton();
        Reservaspanel = new javax.swing.JPanel();
        VerMenupanel = new javax.swing.JPanel();
        Mesaspanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        comboRestaurantes = new javax.swing.JComboBox<>();
        tablaMesas = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SISTEMA DE GESTION DE RESERVAS DE RESTAURANTES");

        panelTabs.setBackground(new java.awt.Color(255, 204, 102));
        panelTabs.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelTabs.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        panelTabs.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelTabs.setOpaque(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CLIENTES REGISTRADOS");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("REGISTRAR CLIENTES NUEVOS");

        jLabel4.setText("NOMBRE COMPLETO");

        jLabel5.setText("EMAIL ");

        jLabel6.setText("TELEFONO");

        jLabel7.setText("ES VEGETARINO?");

        Registrarbotton.setText("REGISTRAR");
        Registrarbotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarbottonActionPerformed(evt);
            }
        });

        prefclifield.setText("SI/NO");

        javax.swing.GroupLayout ClientespanelLayout = new javax.swing.GroupLayout(Clientespanel);
        Clientespanel.setLayout(ClientespanelLayout);
        ClientespanelLayout.setHorizontalGroup(
            ClientespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClientespanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(ClientespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ClientespanelLayout.createSequentialGroup()
                        .addGroup(ClientespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ClientespanelLayout.createSequentialGroup()
                                .addGroup(ClientespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(ClientespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nombreclifield, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                    .addComponent(emailclifield)
                                    .addComponent(telefonoclifield)
                                    .addComponent(prefclifield, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(ClientespanelLayout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(Registrarbotton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(ClientespanelLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112))))
        );
        ClientespanelLayout.setVerticalGroup(
            ClientespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClientespanelLayout.createSequentialGroup()
                .addGroup(ClientespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ClientespanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(ClientespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ClientespanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(ClientespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nombreclifield, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(ClientespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(emailclifield, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ClientespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(telefonoclifield, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ClientespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prefclifield, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(Registrarbotton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ClientespanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        panelTabs.addTab("CLIENTES", Clientespanel);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("REGISTRAR NUEVO RESTAURANTE");

        jLabel9.setText("NOMBRE");

        jLabel10.setText("DIRECCION");

        jLabel11.setText("TELEFONO");

        regisrestbtn.setText("REGISTRAR");
        regisrestbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regisrestbtnActionPerformed(evt);
            }
        });

        jLabel12.setText("CAPACIDAD DE LA MESA");

        agregarMesabtn.setText("AGREGAR MESA");
        agregarMesabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarMesabtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RestaurantespanelLayout = new javax.swing.GroupLayout(Restaurantespanel);
        Restaurantespanel.setLayout(RestaurantespanelLayout);
        RestaurantespanelLayout.setHorizontalGroup(
            RestaurantespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RestaurantespanelLayout.createSequentialGroup()
                .addGroup(RestaurantespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RestaurantespanelLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(regisrestbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RestaurantespanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(RestaurantespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(RestaurantespanelLayout.createSequentialGroup()
                                .addGroup(RestaurantespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(RestaurantespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nombrerestfield)
                                    .addComponent(direccionresfield)
                                    .addComponent(telefonoresfield, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)))
                            .addGroup(RestaurantespanelLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(capacidadMesafield, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))))
                    .addGroup(RestaurantespanelLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(agregarMesabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(RestaurantespanelLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RestaurantespanelLayout.setVerticalGroup(
            RestaurantespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RestaurantespanelLayout.createSequentialGroup()
                .addGap(0, 88, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGroup(RestaurantespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RestaurantespanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(RestaurantespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nombrerestfield, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(RestaurantespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(direccionresfield, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(RestaurantespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(telefonoresfield, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)))
                    .addGroup(RestaurantespanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(regisrestbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(RestaurantespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(capacidadMesafield, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(agregarMesabtn)
                .addGap(43, 43, 43))
        );

        panelTabs.addTab("RESTAURANTES", Restaurantespanel);

        javax.swing.GroupLayout menuspanelLayout = new javax.swing.GroupLayout(menuspanel);
        menuspanel.setLayout(menuspanelLayout);
        menuspanelLayout.setHorizontalGroup(
            menuspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 735, Short.MAX_VALUE)
        );
        menuspanelLayout.setVerticalGroup(
            menuspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        panelTabs.addTab("MENUS", menuspanel);

        jLabel14.setText("SELECCIONE RESTAURANTE");

        comboRestaurantesInventario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboRestaurantesInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRestaurantesInventarioActionPerformed(evt);
            }
        });

        btnCargarInventario.setText("CARGAR INVENTARIO");

        tablaPlatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tablaPlatos);

        dasdasd.setText("NOMBRE");

        jLabel15.setText("AGREGAR PLATOS AL INVENTARIO");

        jLabel16.setText("DESCIPCION");

        jLabel17.setText("PRECIO");

        chkActivoPlato.setText("DISPONIBLE");

        btnAgregarPlato.setText("AGREGAR PLATO");
        btnAgregarPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPlatoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPlatosLayout = new javax.swing.GroupLayout(panelPlatos);
        panelPlatos.setLayout(panelPlatosLayout);
        panelPlatosLayout.setHorizontalGroup(
            panelPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPlatosLayout.createSequentialGroup()
                .addGroup(panelPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPlatosLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPlatosLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(panelPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(dasdasd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(panelPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombrePlato)
                            .addComponent(txtDescripcionPlato)
                            .addComponent(txtPrecioPlato, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)))
                    .addGroup(panelPlatosLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(panelPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgregarPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkActivoPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelPlatosLayout.setVerticalGroup(
            panelPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPlatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPlatosLayout.createSequentialGroup()
                        .addGap(0, 30, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPlatosLayout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombrePlato, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(dasdasd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescripcionPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPrecioPlato, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkActivoPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregarPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        tabInventario.addTab("PLATOS", panelPlatos);

        tablaBebidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tablaBebidas);

        jLabel18.setText("AGREGAR NUEVAS BEBIDA");

        jLabel19.setText("NOMBRE");

        jLabel20.setText("DESCRIPCION");

        jLabel21.setText("PRECIO");

        txtNombreBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreBebidaActionPerformed(evt);
            }
        });

        chkDisponibleBebida.setLabel("DISPONIBLE?");

        chkAlcoholicaBebida.setLabel("CONTIENE ALCOHOL?");
        chkAlcoholicaBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAlcoholicaBebidaActionPerformed(evt);
            }
        });

        btnAgregarBebida.setLabel("AGREGAR BEBIDA");
        btnAgregarBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarBebidaActionPerformed(evt);
            }
        });

        jLabel27.setText("VOLUMEN");

        javax.swing.GroupLayout panelBebidasLayout = new javax.swing.GroupLayout(panelBebidas);
        panelBebidas.setLayout(panelBebidasLayout);
        panelBebidasLayout.setHorizontalGroup(
            panelBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBebidasLayout.createSequentialGroup()
                .addGroup(panelBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelBebidasLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBebidasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBebidasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescripcionBebida))
                    .addGroup(panelBebidasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecioBebida))
                    .addGroup(panelBebidasLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(panelBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkDisponibleBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkAlcoholicaBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelBebidasLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btnAgregarBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBebidasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelBebidasLayout.setVerticalGroup(
            panelBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panelBebidasLayout.createSequentialGroup()
                .addGap(0, 39, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelBebidasLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(panelBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombreBebida, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDescripcionBebida, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPrecioBebida, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkDisponibleBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkAlcoholicaBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregarBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabInventario.addTab("BEBIDAS", panelBebidas);

        panelPostres.setOpaque(false);

        tablaPostres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tablaPostres);

        jLabel22.setText("AGREGAR NUEVOS POSTRES");

        jLabel23.setText("NOMBRE");

        jLabel24.setText("DESCRIPCION");

        jLabel25.setText("PRECIO");

        txtNombrePostre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombrePostreActionPerformed(evt);
            }
        });

        chkDisponiblePostre.setText("DISPONIBLE?");

        chkAptoCeliacos.setText("APTO PARA DIABETICOS?");
        chkAptoCeliacos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAptoCeliacosActionPerformed(evt);
            }
        });

        jLabel26.setText("CALORIAS");

        btnAgregarPostre.setText("AGREGAR POSTRE");

        javax.swing.GroupLayout panelPostresLayout = new javax.swing.GroupLayout(panelPostres);
        panelPostres.setLayout(panelPostresLayout);
        panelPostresLayout.setHorizontalGroup(
            panelPostresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPostresLayout.createSequentialGroup()
                .addGroup(panelPostresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelPostresLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPostresLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombrePostre))
                    .addGroup(panelPostresLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDescripcionPostre))
                    .addGroup(panelPostresLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPrecioPostre))
                    .addGroup(panelPostresLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(panelPostresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkDisponiblePostre, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkAptoCeliacos, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelPostresLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCaloriasPostre))
                    .addGroup(panelPostresLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(btnAgregarPostre, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelPostresLayout.setVerticalGroup(
            panelPostresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPostresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPostresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombrePostre, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPostresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDescripcionPostre, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPostresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPrecioPostre, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkDisponiblePostre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkAptoCeliacos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPostresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCaloriasPostre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAgregarPostre, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPostresLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabInventario.addTab("POSTRES", panelPostres);

        javax.swing.GroupLayout InventariospanelLayout = new javax.swing.GroupLayout(Inventariospanel);
        Inventariospanel.setLayout(InventariospanelLayout);
        InventariospanelLayout.setHorizontalGroup(
            InventariospanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InventariospanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(comboRestaurantesInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(btnCargarInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(InventariospanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabInventario)
                .addContainerGap())
        );
        InventariospanelLayout.setVerticalGroup(
            InventariospanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InventariospanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InventariospanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCargarInventario, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(comboRestaurantesInventario)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabInventario))
        );

        panelTabs.addTab("INVENTARIO", Inventariospanel);

        javax.swing.GroupLayout ReservaspanelLayout = new javax.swing.GroupLayout(Reservaspanel);
        Reservaspanel.setLayout(ReservaspanelLayout);
        ReservaspanelLayout.setHorizontalGroup(
            ReservaspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 735, Short.MAX_VALUE)
        );
        ReservaspanelLayout.setVerticalGroup(
            ReservaspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        panelTabs.addTab("RESERVAS", Reservaspanel);

        javax.swing.GroupLayout VerMenupanelLayout = new javax.swing.GroupLayout(VerMenupanel);
        VerMenupanel.setLayout(VerMenupanelLayout);
        VerMenupanelLayout.setHorizontalGroup(
            VerMenupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 735, Short.MAX_VALUE)
        );
        VerMenupanelLayout.setVerticalGroup(
            VerMenupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        panelTabs.addTab("VER MENU", VerMenupanel);

        jLabel13.setText("SELECCIONA RESTAURANTES");

        comboRestaurantes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboRestaurantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRestaurantesActionPerformed(evt);
            }
        });

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaMesas.setViewportView(jTable4);

        javax.swing.GroupLayout MesaspanelLayout = new javax.swing.GroupLayout(Mesaspanel);
        Mesaspanel.setLayout(MesaspanelLayout);
        MesaspanelLayout.setHorizontalGroup(
            MesaspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MesaspanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(MesaspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tablaMesas, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MesaspanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(comboRestaurantes, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        MesaspanelLayout.setVerticalGroup(
            MesaspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MesaspanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(MesaspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboRestaurantes, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tablaMesas, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelTabs.addTab("VER MESAS", Mesaspanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTabs)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTabs)
                .addContainerGap())
        );

        panelTabs.getAccessibleContext().setAccessibleName("panñetabs");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarbottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarbottonActionPerformed
        registrarCliente();    }//GEN-LAST:event_RegistrarbottonActionPerformed

    private void regisrestbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regisrestbtnActionPerformed
        registrarRestaurante();
    }//GEN-LAST:event_regisrestbtnActionPerformed

    private void agregarMesabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarMesabtnActionPerformed
        agregarMesaARestaurante();
    }//GEN-LAST:event_agregarMesabtnActionPerformed

    private void comboRestaurantesInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRestaurantesInventarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboRestaurantesInventarioActionPerformed

    private void btnAgregarPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPlatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarPlatoActionPerformed

    private void txtNombreBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreBebidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreBebidaActionPerformed

    private void txtNombrePostreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombrePostreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombrePostreActionPerformed

    private void chkAptoCeliacosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAptoCeliacosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAptoCeliacosActionPerformed

    private void chkAlcoholicaBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAlcoholicaBebidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAlcoholicaBebidaActionPerformed

    private void btnAgregarBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarBebidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarBebidaActionPerformed

    private void comboRestaurantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRestaurantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboRestaurantesActionPerformed
private void agregarMesaARestaurante() {
    int filaSeleccionada = jTable2.getSelectedRow();
    if (filaSeleccionada == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Selecciona un restaurante en la tabla.");
        return;
    }

    String capacidadStr = capacidadMesafield.getText();
    if (capacidadStr.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Ingresa la capacidad de la mesa.");
        return;
    }

    try {
        int capacidad = Integer.parseInt(capacidadStr);
        Restaurante restaurante = listaRestaurantes.get(filaSeleccionada);
        int idMesa = restaurante.getMesasDisponibles().size() + 1;

        MODELO.Mesa nuevaMesa = new MODELO.Mesa(idMesa, capacidad);
        restaurante.agregarMesa(nuevaMesa);

        javax.swing.JOptionPane.showMessageDialog(this, "Mesa agregada exitosamente.");

        capacidadMesafield.setText("");
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "La capacidad debe ser un número entero.");
            javax.swing.JOptionPane.showMessageDialog(this, "Mesa agregada exitosamente.");
        capacidadMesafield.setText("");

        // Si el restaurante de la tabla es el mismo que el del combo, actualiza la tabla
        if (comboRestaurantes.getSelectedIndex() == filaSeleccionada) {
            mostrarMesasDeRestauranteSeleccionado();
        }

    }
}
private void actualizarCombosRestaurantes
        () {
    comboRestaurantes.removeAllItems();
    for (Restaurante r : listaRestaurantes) {
        comboRestaurantes.addItem(r.getNombre());
        comboRestaurantesInventario.addItem(r.getNombre());
    }
    
    
    
}

private void mostrarMesasDeRestauranteSeleccionado() {
    int index = comboRestaurantes.getSelectedIndex();
    if (index == -1) return;

    Restaurante restaurante = listaRestaurantes.get(index);
    modeloTablaMesas.setRowCount(0); // limpiar tabla

    for (MODELO.Mesa mesa : restaurante.getMesasDisponibles()) {
        modeloTablaMesas.addRow(new Object[]{
            mesa.getId(),
            mesa.getCapacidad(),
            mesa.isDisponible() ? "Sí" : "No"
        });
    }
}

    private void registrarRestaurante() {
    String nombre = nombrerestfield.getText();
    String direccion = direccionresfield.getText();
    String telefono = telefonoresfield.getText();

    if (nombre.isEmpty() || direccion.isEmpty() || telefono.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Completa todos los campos del restaurante.");
        return;
    }

    Restaurante nuevo = new Restaurante(idRestaurante++, nombre, direccion, telefono);
    listaRestaurantes.add(nuevo);

    modeloTablaRestaurantes.addRow(new Object[]{
        nuevo.getId(),
        nuevo.getNombre(),
        nuevo.getDireccion(),
        nuevo.getTelefono()
    });

    nombrerestfield.setText("");
    direccionresfield.setText("");
    telefonoresfield.setText("");
    actualizarCombosRestaurantes();

}

    private void registrarCliente() {
    String nombre = nombreclifield.getText();
    String email = emailclifield.getText();
    String telefono = telefonoclifield.getText();
    boolean vegetariano = prefclifield.isSelected();

    if (nombre.isEmpty() || email.isEmpty() || telefono.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Completa todos los campos");
        return;
    }

    Cliente nuevo = new Cliente(idCliente++, nombre, email, telefono, vegetariano);
    listaClientes.add(nuevo);

    modeloTabla.addRow(new Object[]{
        nuevo.getId(),
        nuevo.getNombre(),
        nuevo.getEmail(),
        nuevo.getTelefono(),
        nuevo.getPreferencia() ? "Sí" : "No"
    });

    // Limpiar campos
    nombreclifield.setText("");
    emailclifield.setText("");
    telefonoclifield.setText("");
    prefclifield.setSelected(false);
}
   private void configurarTablasInventario() {
    // Configuración para tabla de platos
    DefaultTableModel modeloTablaPlatos = new DefaultTableModel();
    modeloTablaPlatos.addColumn("ID");
    modeloTablaPlatos.addColumn("Nombre");
    modeloTablaPlatos.addColumn("Descripción");
    modeloTablaPlatos.addColumn("Precio");
    modeloTablaPlatos.addColumn("Estado");
    tablaPlatos.setModel(modeloTablaPlatos);

    // Configuración para tabla de bebidas
    DefaultTableModel modeloTablaBebidas = new DefaultTableModel();
    modeloTablaBebidas.addColumn("ID");
    modeloTablaBebidas.addColumn("Nombre");
    modeloTablaBebidas.addColumn("Descripción");
    modeloTablaBebidas.addColumn("Precio");
    modeloTablaBebidas.addColumn("Estado");
    modeloTablaBebidas.addColumn("Alcohólica");
    modeloTablaBebidas.addColumn("Volumen");
    tablaBebidas.setModel(modeloTablaBebidas);

    // Configuración para tabla de postres
    DefaultTableModel modeloTablaPostres = new DefaultTableModel();
    modeloTablaPostres.addColumn("ID");
    modeloTablaPostres.addColumn("Nombre");
    modeloTablaPostres.addColumn("Descripción");
    modeloTablaPostres.addColumn("Precio");
    modeloTablaPostres.addColumn("Estado");
    modeloTablaPostres.addColumn("Apto Celiacos");
    modeloTablaPostres.addColumn("Calorías");
    tablaPostres.setModel(modeloTablaPostres);
}



private void configurarEventListeners() {
    btnCargarInventario.addActionListener(e -> cargarInventarioRestaurante());
    btnAgregarPlato.addActionListener(e -> agregarPlato());
    btnAgregarBebida.addActionListener(e -> agregarBebida());
    btnAgregarPostre.addActionListener(e -> agregarPostre());
}
private void cargarInventarioRestaurante() {
    int index = comboRestaurantesInventario.getSelectedIndex();
    if (index == -1) {
        JOptionPane.showMessageDialog(this, "Selecciona un restaurante primero");
        return;
    }
    
    Restaurante restaurante = listaRestaurantes.get(index);
    actualizarTablaPlatos(restaurante);
    actualizarTablaBebidas(restaurante);
    actualizarTablaPostres(restaurante);
}

private void actualizarTablaPlatos(Restaurante restaurante) {
    DefaultTableModel modelo = (DefaultTableModel) tablaPlatos.getModel();
    modelo.setRowCount(0);
    
    for (Plato p : restaurante.getInventarioPlatos().listar()) {
        modelo.addRow(new Object[]{
            p.getId(),
            p.getNombre(),
            p.getDescripcion(),
            p.getPrecio(),
            p.isEstado() ? "Disponible" : "No disponible"
        });
    }
}

private void actualizarTablaBebidas(Restaurante restaurante) {
    DefaultTableModel modelo = (DefaultTableModel) tablaBebidas.getModel();
    modelo.setRowCount(0);
    
    for (Bebidas b : restaurante.getInventarioBebidas().listar()) {
        modelo.addRow(new Object[]{
            b.getId(),
            b.getNombre(),
            b.getDescripcion(),
            b.getPrecio(),
            b.isEstado() ? "Disponible" : "No disponible",
            b.isAlcoholica() ? "Sí" : "No",
            b.getVolumen()
        });
    }
}

private void actualizarTablaPostres(Restaurante restaurante) {
    DefaultTableModel modelo = (DefaultTableModel) tablaPostres.getModel();
    modelo.setRowCount(0);
    
    for (Postres p : restaurante.getInventarioPostres().listar()) {
        modelo.addRow(new Object[]{
            p.getId(),
            p.getNombre(),
            p.getDescripcion(),
            p.getPrecio(),
            p.isEstado() ? "Disponible" : "No disponible",
            p.isAptoCeliacos() ? "Sí" : "No",
            p.getCalorias()
        });
    }
}
private void agregarPlato() {
    int index = comboRestaurantesInventario.getSelectedIndex();
    if (index == -1) {
        JOptionPane.showMessageDialog(this, "Selecciona un restaurante primero");
        return;
    }
    
    try {
        Restaurante restaurante = listaRestaurantes.get(index);
        Plato nuevo = new Plato(
            restaurante.getInventarioPlatos().cantidad() + 1,
            txtNombrePlato.getText(),
            txtDescripcionPlato.getText(),
            Double.parseDouble(txtPrecioPlato.getText()),
            chkActivoPlato.isSelected()
        );
        
        restaurante.agregarPlato(nuevo);
        actualizarTablaPlatos(restaurante);
        limpiarCamposPlato();
        
        JOptionPane.showMessageDialog(this, "Plato agregado exitosamente");
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Ingresa un precio válido");
    }
}

private void limpiarCamposPlato() {
    txtNombrePlato.setText("");
    txtDescripcionPlato.setText("");
    txtPrecioPlato.setText("");
    chkActivoPlato.setSelected(false);
}

private void agregarBebida() {
    int index = comboRestaurantesInventario.getSelectedIndex();
    if (index == -1) {
        JOptionPane.showMessageDialog(this, "Selecciona un restaurante primero");
        return;
    }
    
    try {
        Restaurante restaurante = listaRestaurantes.get(index);
        Bebidas nueva = new Bebidas(
            restaurante.getInventarioBebidas().cantidad() + 1,
            txtNombreBebida.getText(),
            txtDescripcionBebida.getText(),
            Double.parseDouble(txtPrecioBebida.getText()),
            chkDisponibleBebida.isSelected(),
            chkAlcoholicaBebida.isSelected(),
            jTextField1.getText()
        );
        
        restaurante.agregarBebida(nueva);
        actualizarTablaBebidas(restaurante);
        limpiarCamposBebida();
        
        JOptionPane.showMessageDialog(this, "Bebida agregada exitosamente");
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Ingresa un precio válido");
    }
}

private void limpiarCamposBebida() {
    txtNombreBebida.setText("");
    txtDescripcionBebida.setText("");
    txtPrecioBebida.setText("");
    jTextField1.setText("");
    chkDisponibleBebida.setSelected(false);
    chkAlcoholicaBebida.setSelected(false);
}

private void agregarPostre() {
    int index = comboRestaurantesInventario.getSelectedIndex();
    if (index == -1) {
        JOptionPane.showMessageDialog(this, "Selecciona un restaurante primero");
        return;
    }
    
    try {
        Restaurante restaurante = listaRestaurantes.get(index);
        Postres nuevo = new Postres(
            restaurante.getInventarioPostres().cantidad() + 1,
            txtNombrePostre.getText(),
            txtDescripcionPostre.getText(),
            Double.parseDouble(txtPrecioPostre.getText()),
            chkDisponiblePostre.isSelected(),
            chkAptoCeliacos.isSelected(),
            Integer.parseInt(txtCaloriasPostre.getText())
        );
        
        restaurante.agregarPostre(nuevo);
        actualizarTablaPostres(restaurante);
        limpiarCamposPostre();
        
        JOptionPane.showMessageDialog(this, "Postre agregado exitosamente");
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Ingresa un precio y calorías válidos");
    }
}

private void limpiarCamposPostre() {
    txtNombrePostre.setText("");
    txtDescripcionPostre.setText("");
    txtPrecioPostre.setText("");
    txtCaloriasPostre.setText("");
    chkDisponiblePostre.setSelected(false);
    chkAptoCeliacos.setSelected(false);
}
private void mostrarMenuRestaurante() {
    int index = comboRestaurantes.getSelectedIndex();
    if (index == -1) return;
    
    Restaurante restaurante = listaRestaurantes.get(index);
    
    if (restaurante.getMenu() == null) {
        restaurante.cargarMenuDesdeInventarios();
    }
    
    // Implementa la lógica para mostrar el menú en la pestaña correspondiente
    // Puedes usar un JTextArea o una tabla similar a las de inventario
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Clientespanel;
    private javax.swing.JPanel Inventariospanel;
    private javax.swing.JPanel Mesaspanel;
    private javax.swing.JButton Registrarbotton;
    private javax.swing.JPanel Reservaspanel;
    private javax.swing.JPanel Restaurantespanel;
    private javax.swing.JPanel VerMenupanel;
    private javax.swing.JButton agregarMesabtn;
    private javax.swing.JButton btnAgregarBebida;
    private javax.swing.JButton btnAgregarPlato;
    private javax.swing.JButton btnAgregarPostre;
    private javax.swing.JButton btnCargarInventario;
    private javax.swing.JTextField capacidadMesafield;
    private javax.swing.JCheckBox chkActivoPlato;
    private javax.swing.JCheckBox chkAlcoholicaBebida;
    private javax.swing.JCheckBox chkAptoCeliacos;
    private javax.swing.JCheckBox chkDisponibleBebida;
    private javax.swing.JCheckBox chkDisponiblePostre;
    private javax.swing.JComboBox<String> comboRestaurantes;
    private javax.swing.JComboBox<String> comboRestaurantesInventario;
    private javax.swing.JLabel dasdasd;
    private javax.swing.JTextField direccionresfield;
    private javax.swing.JTextField emailclifield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel menuspanel;
    private javax.swing.JTextField nombreclifield;
    private javax.swing.JTextField nombrerestfield;
    private javax.swing.JPanel panelBebidas;
    private javax.swing.JPanel panelPlatos;
    private javax.swing.JPanel panelPostres;
    private javax.swing.JTabbedPane panelTabs;
    private javax.swing.JCheckBox prefclifield;
    private javax.swing.JButton regisrestbtn;
    private javax.swing.JTabbedPane tabInventario;
    private javax.swing.JTable tablaBebidas;
    private javax.swing.JScrollPane tablaMesas;
    private javax.swing.JTable tablaPlatos;
    private javax.swing.JTable tablaPostres;
    private javax.swing.JTextField telefonoclifield;
    private javax.swing.JTextField telefonoresfield;
    private javax.swing.JTextField txtCaloriasPostre;
    private javax.swing.JTextField txtDescripcionBebida;
    private javax.swing.JTextField txtDescripcionPlato;
    private javax.swing.JTextField txtDescripcionPostre;
    private javax.swing.JTextField txtNombreBebida;
    private javax.swing.JTextField txtNombrePlato;
    private javax.swing.JTextField txtNombrePostre;
    private javax.swing.JTextField txtPrecioBebida;
    private javax.swing.JTextField txtPrecioPlato;
    private javax.swing.JTextField txtPrecioPostre;
    // End of variables declaration//GEN-END:variables
}
